name: CI - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Caching is handled by the setup-java action in v4
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3 # Note: v3 is the current stable version for this action

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Detekt reports
        uses: actions/upload-artifact@v4
        if: always() # Always run this step to upload reports even if the build fails
        with:
          name: detekt-reports
          path: '**/build/reports/detekt/detekt.*'

      - name: Upload JaCoCo reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-reports
          path: '**/build/reports/jacoco/test/html/**'
